// Parametric Optical Spacer - E-Dermatologist (Mobile Spacer Edition)
// Auto-generated by hardware/spacer_generator.py
// Units: millimetres. Render with F6 then export STL.

HEIGHT        = 35.0;
TOP_APERTURE  = 14.0;
BASE_CLEAR    = 38.0;
BASE_OUTER    = 48.0;
WALL_TOP      = 2.0;
SEG           = 128;

module spacer() {
    difference() {
        // Outer body: widening base flange tapering to the camera aperture.
        cylinder(h = HEIGHT,
                 d1 = BASE_OUTER,
                 d2 = TOP_APERTURE + 2 * WALL_TOP,
                 $fn = SEG);
        // Inner cavity: clear optical path.
        translate([0, 0, -0.01])
            cylinder(h = HEIGHT + 0.02,
                     d1 = BASE_CLEAR,
                     d2 = TOP_APERTURE,
                     $fn = SEG);
    }
}

spacer();
